version: '3.8'

services:
  # Servicio de Nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - tputn_app-network

  # Servicio de PHP-FPM
  php-fpm:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    container_name: php-fpm
    volumes:
      - ./:/var/www
      - ./vendor:/var/www/vendor
      - ./public:/var/www/html
      - ./src/:/var/www/src
    working_dir: /var/www
    networks:
      - tputn_app-network

networks:
  tputn_app-network:
#    driver: bridge
    external: true
